name: Lint
on: [push, pull_request]
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup
      run: |
        pip install mypy
        pip install -r requirements.txt
        mypy src > /dev/null || true
        yes | mypy --install-types
    - name: run mypy
      run: |
        mypy --strict src
